# exPress Model Configuration
seed: 42
exp_name: "exPress_experiment"
mode: "train"
ckpt_path: null
model_type: "exPress"

# Data settings
data:
  root_path: "path/to/generated/dataset"
  wo_vel: false
  batch_size: 32
  val_split_ratio: 0.2
  num_workers: 4
  pin_memory: true
  press_threshold: 0.9

trainer:
  max_epochs: 200
  min_epochs: 10
  gradient_clip_val: 2.0
  devices: [0]
  accelerator: "gpu"

optimizer:
  optimizer_params:
    lr: 1e-4
    weight_decay: 1e-5

model:
  in_channels: 19
  num_gnn_layers: 2
  gnn_hidden_dim: 64
  num_lstm_layers: 2
  lstm_hidden_dim: 64
  lstm_dropout: 0.4
  lstm_bidirectional: true
  use_pressing_features: false
  gnn_type: gat # "gat", "gatv2", "gin", "sage"
  gnn_head: 4
  pos_weight: 

early_stop:
  monitor_metric: "val_loss"
  patience: 50
  min_delta: 1e-3
  mode: "min"
  strict: false
  verbose: true

checkpoint:
  monitor_metric: "val_loss"
  save_top_k: 1
  verbose: true
  mode: "min" 

# Logging settings
logging:
  use_wandb: false
  wandb:
    project: "Pressing-Evaluation"
    entity: null
    api_key: null
    log_model: true
    save_code: true

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher